# create REJECT_WITH chain that does different rejects for tcp/udp
iptables -N REJECT_WITH
iptables -A REJECT_WITH -p tcp -j REJECT --reject-with tcp-reset
iptables -A REJECT_WITH -j REJECT --reject-with icmp-port-unreachable
#
iptables -N BLACK_LIST
iptables -A BLACK_LIST -j LOG --log-prefix "adding to BLACKLIST: "
iptables -A BLACK_LIST -m recent --name BLACKLIST --set -j DROP
#
#
# on external hosts, do rate limiting on incoming ssh packets, and keep a blacklist for 300 seconds
# this rule drops *any* packet if the IP is in the blacklist
# icmp 'destination-unreachable' packets should not update BLACKLIST, because
# they are generated by our own REJECT rule in the extern_out chain
iptables -A INPUT -i eth0 -m recent --name BLACKLIST --update --seconds 600 -j DROP
#
# all *established* ssh connections simply continue
iptables -A INPUT -i eth0  -p tcp --dport 22 -m state --state ESTABLISHED,RELATED -j ACCEPT
#
# *new* ssh connections are all put into a list 'NEW_SSH', and if there are 3 such packets in 300 seconds
# we send the package to chain 'BLACK_LIST' which puts the IP in the blacklist
iptables -A INPUT -i eth0  -p tcp --dport 22 -m state --state NEW -m recent --name NEW_SSH --rcheck --seconds 300 --hitcount 3 -j BLACK_LIST
#
# if we have seen less then 3 such packets in the last 300 seconds we accept
iptables -A INPUT -i eth0  -p tcp --dport 22 -m state --state NEW -m recent --name NEW_SSH --set -j ACCEPT
#
# if the destination address is in the blacklist, we REJECT *any* packet
iptables -A OUTPUT -o eth0 -m recent --name BLACKLIST --rdest --rcheck --seconds 300 -j REJECT_WITH
#
# outgoing we accept all ssh traffic, with connection tracking
iptables -A OUTPUT -o eth0 -p tcp --sport 22 -m state --state ESTABLISHED,NEW,RELATED -j ACCEPT


"""
:INPUT DROP [0:0]
:OUTPUT ACCEPT [0:0]
:ssh-ban - [0:0]
:ssh-check - [0:0]

-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW -j ssh-check

-A ssh-check -m recent --name SSH --set --mask 255.255.255.255 --rsource
-A ssh-check -m recent --name SSH --rcheck --mask 255.255.255.255 --rsource --seconds 20 --hitcount 3 -j ssh-ban
-A ssh-check -j ACCEPT

-A ssh-ban -j LOG --log-prefix "anti-bruteforce ssh:" --log-level info
-A ssh-ban -j DROP
"""